classDiagram
IComponentAbstractFactory..|>BluComponentAbstractFactory
IComponentAbstractFactory..|>GreenComponentAbstractFactory
BluLabel--|>ILabel
BluButton--|>IButton
GreenLabel--|>ILabel
GreenButton--|>IButton
BluComponentAbstractFactory..>BluButton
BluComponentAbstractFactory..>BluLabel
GreenComponentAbstractFactory..>GreenButton
GreenComponentAbstractFactory..>GreenLabel
class IComponentAbstractFactory{
    <<interface>>
GetButton()
GetLabel()
}
class BluComponentAbstractFactory{
GetButton()
GetLabel()
}
class GreenComponentAbstractFactory{
GetButton()
GetLabel()
}
class IButton{
    <<interface>>
DoSomething()
}
class GreenButton{
DoSomething()
}
class BluButton{
Create()
}
class GreenLabel{
DoSomething()
}
class BluLabel{
DoSomething()
}
class ILabel{
    <<interface>>
DoSomething()
}